version: "3.8"

services:

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER:      langgraph
      POSTGRES_PASSWORD:  RickSanchez2025
      POSTGRES_DB:        langgraph
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5433:5432"

  web:
    build: .
    ports:
      - "8502:8501"    # host 8502 → container 8501
    environment:
      OPENAI_API_KEY:             ${OPENAI_API_KEY}
      PGVECTOR_CONNECTION_STRING: "postgresql://langgraph:RickSanchez2025@postgres:5432/langgraph"
      PGVECTOR_COLLECTION_NAME:   "ai_pipeline_memory"
      VECTOR_DECAY_RATE:          "0.01"
      VECTOR_RETRIEVAL_K:         "6"
    depends_on:
      - postgres

volumes:
  pgdata:
