services:

  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: langgraph
      POSTGRES_PASSWORD: RickSanchez2025
      POSTGRES_DB: langgraph
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5433:5432"  # host:container – avoid conflict with local PG

  web:
    build: .
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8501:8501"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      PGVECTOR_CONNECTION_STRING: postgresql://langgraph:RickSanchez2025@postgres:5432/langgraph
      PGVECTOR_COLLECTION_NAME: vector_memory
      VECTOR_DECAY_RATE: "0.01"
      VECTOR_RETRIEVAL_K: "6"
      VECTOR_TTL_DAYS: "30"
      CHAT_HISTORY_DIR: ./data/history
      FEEDBACK_LOG_DIR: ./data
      MAX_HISTORY_LENGTH: "100"
    command: >
      sh -c "
        until pg_isready -h postgres -p 5432; do
          echo 'Waiting for Postgres...';
          sleep 1;
        done &&
        alembic upgrade head &&
        streamlit run streamlit_ui.py --server.port=8501 --server.address=0.0.0.0
      "

volumes:
  pgdata:
