version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: langgraph_postgres
    environment:
      POSTGRES_USER: langgraph
      POSTGRES_DB: langgraph
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    secrets:
      - db_password
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: langgraph_web
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PGVECTOR_CONNECTION_STRING=postgresql://langgraph:${DB_PASSWORD}@postgres:5432/langgraph
    ports:
      - "8502:8501"
    depends_on:
      - postgres
    secrets:
      - db_password

volumes:
  postgres_data:

secrets:
  db_password:
    file: ./secrets/db_password
